import json
from text_to_lan import TextToLan

UI_ENGLISH = {
    # --- NAVIGATION ---
    'nav_home': 'Home',
    'nav_upload': 'Upload',
    'nav_login': 'Login',
    
    # --- HERO & HOME ---
    'hero_title': 'Master Tomorrow’s Skills Today',
    'hero_desc': 'Explore expert-led courses, advance your career, and learn at your own pace.',
    'btn_start': 'Get Started',
    'pop_courses': '🔥 Popular Courses',
    'no_courses': 'No courses uploaded yet. Click Upload to start!',
    'btn_learn': 'Learn Now',

    # --- FEATURES & REVIEWS ---
    'why_choose': 'Why Choose MyLMS?',
    'why_desc': 'MyLMS is a modern learning platform built to help students and professionals learn new skills.',
    'feat_1_title': '🎯 Expert-Led Courses',
    'feat_1_desc': 'Learn directly from industry professionals.',
    'feat_2_title': '📚 Wide Range of Topics',
    'feat_2_desc': 'Explore 100+ high-quality courses.',
    'feat_3_title': '⏳ Learn Anytime',
    'feat_3_desc': 'Access your courses anytime, anywhere.',
    'reviews_title': 'What Our Learners Say',
    'review_1': '“Amazing platform! I learned Python within 30 days.”',
    'review_2': '“The courses are very clear and beginner-friendly.”',
    'review_3': '“Loved the hands-on projects! Highly recommended.”',
    'footer_text': '© 2025 LMS Portal • Multi-language learning experience',

    # --- UPLOAD PAGE ---
    'upload_title': 'Upload Video',
    'upload_header': 'Details',
    'video_label': 'Video File (Required)',
    'select_video': 'Select Video to Upload',
    'drag_drop': 'Drag and drop video files to upload',
    'title_placeholder': 'Add a title that describes your video',
    'desc_placeholder': 'Tell viewers about your video',
    'lang_settings': 'Language Settings',
    'video_lang': 'Video Language',
    'target_lang': 'Target Language',
    'btn_upload': 'Upload',
    'btn_uploading': 'Uploading...',
    'processing_title': 'AI is Processing...',
    'processing_desc': 'Extracting Audio • Translating • Dubbing',

    # --- VIEW PAGE (Missing Keys Added Below) ---
    'sidebar_title': 'Content Localization',
    'sidebar_sub': 'Learn in your language',
    'profile_header': 'Profile',
    'user_level': 'Level 3 • 65% complete',
    'interface_lang': 'Interface Language',
    'video_badge': 'Video',
    
    # NEW KEYS FOR MIDDLE SECTION
    'trans_audio_title': 'Translated Audio',
    'choose_audio_label': 'Choose Audio Language:',
    'btn_load': 'Load Audio',
    'loc_section_title': 'Content Localization',
    'loc_section_desc': 'Choose your preferred language for video audio, transcript, and captions.',
    'label_video_audio': 'Video Audio Language',
    'label_captions': 'Caption Language',
    'btn_apply': 'Apply Localization',
    'demo_note': 'This demo updates the UI to match your selected languages.',
    
    # TABS
    'tab_desc': 'Description',
    'tab_res': 'Resources',
    'lesson_overview': 'Lesson Overview',
    'res_title': 'Additional Resources',
    'res_1': 'Slides (PDF)',
    'res_2': 'Practice Quiz',
    'page_subtitle': 'Localized AI Content',
    'generated_date': 'Generated:'
}

TARGET_LANGS = ['ta', 'hi', 'te', 'kn'] 

def run_translation_agent():
    print("🤖 UI Translator Agent Started...")
    final_translations = {'en': UI_ENGLISH}

    for lang in TARGET_LANGS:
        print(f"\n🌍 Translating UI to {lang}...")
        lang_dict = {}
        for key, text in UI_ENGLISH.items():
            try:
                translator = TextToLan(text, target_lang=lang)
                translated_text = translator.eng_to_tamil()
                lang_dict[key] = translated_text
                print(f"   ✅ {key}: {translated_text}")
            except Exception as e:
                print(f"   ❌ Error: {e}")
                lang_dict[key] = text 

        final_translations[lang] = lang_dict

    with open('translations.py', 'w', encoding='utf-8') as f:
        f.write("# Auto-generated by AI Agent\n")
        f.write("TRANSLATIONS = ")
        f.write(json.dumps(final_translations, indent=4, ensure_ascii=False))
    
    print("\n✨ Success! 'translations.py' updated.")

if __name__ == "__main__":
    run_translation_agent()